# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - sky-dev
    - toglenn/host-logs-pipeline

pr:
  branches:
    include:
    - sky-dev
    - toglenn/host-logs-pipeline

variables:
  armServiceConnectionName: 'Sky_MER_Sandbox_Connection'
  subscription: 'b2eb1341-814f-4e78-bec8-6042f4c10c5b'
  containerRegistry: 'ObservabilityACR'
  repoImageName: '${{ variables.containerRegistry }}.azurecr.io/public/azuremonitor/containerinsights/cidev'
  IS_PR: $[eq(variables['Build.Reason'], 'PullRequest')]
  TEMP: $(Agent.TempDirectory)

jobs:
- job: common
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: ComponentGovernanceComponentDetection@0

  - bash: |
      commit=$(git rev-parse --short HEAD)
      datetime=$(date +'%m%d%Y')
      linuxImagetag="$datetime"-"$commit"
      windowsImageTag=win-"$datetime"-"$commit"
      echo "##vso[task.setvariable variable=linuxImagetag;isOutput=true]$linuxImagetag"
      echo "##vso[task.setvariable variable=windowsImageTag;isOutput=true]$windowsImageTag"

      cd $(Build.SourcesDirectory)/deployment/mergebranch-multiarch-agent-deployment/ServiceGroupRoot/Scripts
      tar -czvf ../artifacts.tar.gz pushAgentToAcr.sh

      cd $(Build.SourcesDirectory)/deployment/arc-k8s-extension/ServiceGroupRoot/Scripts
      tar -czvf ../artifacts.tar.gz ../../../../charts/azuremonitor-containers/ pushChartToAcr.sh
    name: setup

  - task: CopyFiles@2
    displayName: "Copy ev2 deployment artifacts"
    inputs:
      SourceFolder: "$(Build.SourcesDirectory)/deployment"
      Contents: |
        **/*
      TargetFolder: '$(Build.ArtifactStagingDirectory)/build'

  - task: CopyFiles@2
    displayName: "Copy ev2 deployment scripts"
    inputs:
      SourceFolder: "$(Build.SourcesDirectory)/.pipelines"
      Contents: |
        **/*.sh
      TargetFolder: '$(Build.ArtifactStagingDirectory)/build'

  - task: CopyFiles@2
    displayName: "Copy ev2 deployment scripts"
    inputs:
      SourceFolder: "$(Build.SourcesDirectory)/kubernetes"
      Contents: |
        *.yaml
      TargetFolder: '$(Build.ArtifactStagingDirectory)/build'

  - task: CopyFiles@2
    displayName: "Copy ev2 deployment scripts"
    inputs:
      SourceFolder: "$(Build.SourcesDirectory)/charts"
      Contents: |
        **/*
      TargetFolder: '$(Build.ArtifactStagingDirectory)/build'

  - task: CopyFiles@2
    displayName: "Copy ev2 deployment scripts"
    inputs:
      SourceFolder: "$(Build.SourcesDirectory)/test/e2e"
      Contents: |
        *.yaml
      TargetFolder: '$(Build.ArtifactStagingDirectory)/build'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: drop

- job: build_windows_2019
  dependsOn:
  -  common
  pool:
    vmImage: 'windows-latest'
  variables:
    windowsImageTag: $[ dependencies.common.outputs['setup.windowsImageTag'] ]
    windows2019BaseImageVersion: ltsc2019
  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        write-host $env:TEMP
        
  
  - task: PowerShell@2
    inputs:
      targetType: 'filePath'
      filePath: $(System.DefaultWorkingDirectory)/scripts/build/windows/install-build-pre-requisites.ps1
    displayName: 'install prereqs'

  - script: |
      setlocal enabledelayedexpansion
      powershell.exe -ExecutionPolicy Unrestricted -NoProfile -WindowStyle Hidden -File "build\hostlogswindows\Makefile.ps1"
      endlocal
      exit /B %ERRORLEVEL%
    displayName: 'build base'

  - task: AzureCLI@2
    displayName: "Docker windows build for ltsc2019"
    inputs:
      azureSubscription: ${{ variables.armServiceConnectionName }}
      scriptType: ps
      scriptLocation: inlineScript
      inlineScript: |
        mkdir -p $(Build.ArtifactStagingDirectory)/windows
        cd kubernetes/windows

        az --version
        az account show
        az account set -s ${{ variables.subscription }}
        az acr login -n ${{ variables.containerRegistry }}

        docker build --isolation=hyperv --tag ${{ variables.repoImageName }}:$(windowsImageTag)-$(windows2019BaseImageVersion) --build-arg WINDOWS_VERSION=$(windows2019BaseImageVersion) --build-arg IMAGE_TAG=$(windowsImageTag) .
        if ("$(Build.Reason)" -ne "PullRequest") {
           docker push ${{ variables.repoImageName }}:$(windowsImageTag)-$(windows2019BaseImageVersion)
        }

- job: build_windows_2022
  dependsOn:
  -  common
  pool:
    vmImage: 'windows-latest'
  variables:
    windowsImageTag: $[ dependencies.common.outputs['setup.windowsImageTag'] ]
    windows2022BaseImageVersion: ltsc2022
  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        write-host $env:TEMP

  - task: PowerShell@2
    inputs:
      targetType: 'filePath'
      filePath: $(System.DefaultWorkingDirectory)/scripts/build/windows/install-build-pre-requisites.ps1
    displayName: 'install prereqs'

  - script: |
      setlocal enabledelayedexpansion
      powershell.exe -ExecutionPolicy Unrestricted -NoProfile -WindowStyle Hidden -File "build\hostlogswindows\Makefile.ps1"
      endlocal
      exit /B %ERRORLEVEL%
    displayName: 'build base'

  - task: AzureCLI@2
    displayName: "Docker windows build for ltsc2022"
    inputs:
      azureSubscription: ${{ variables.armServiceConnectionName }}
      scriptType: ps
      scriptLocation: inlineScript
      inlineScript: |
        mkdir -p $(Build.ArtifactStagingDirectory)/hostlogswindows
        cd kubernetes/windows

        az --version
        az account show
        az account set -s ${{ variables.subscription }}
        az acr login -n ${{ variables.containerRegistry }}

        docker build --isolation=hyperv --tag ${{ variables.repoImageName }}:$(windowsImageTag)-$(windows2022BaseImageVersion) --build-arg WINDOWS_VERSION=$(windows2022BaseImageVersion) --build-arg IMAGE_TAG=$(windowsImageTag) .
        if ("$(Build.Reason)" -ne "PullRequest") {
           docker push ${{ variables.repoImageName }}:$(windowsImageTag)-$(windows2022BaseImageVersion)
        }

- job: build_windows_multi_arc
  dependsOn:
  - common
  - build_windows_2019
  - build_windows_2022
  pool:
    vmImage: 'windows-latest'
  variables:
    windowsImageTag: $[ dependencies.common.outputs['setup.windowsImageTag'] ]
    windows2019BaseImageVersion: ltsc2019
    windows2022BaseImageVersion: ltsc2022
  steps:
  - task: AzureCLI@2
    displayName: "Docker windows build for multi-arc image"
    inputs:
      azureSubscription: ${{ variables.armServiceConnectionName }}
      scriptType: ps
      scriptLocation: inlineScript
      inlineScript: |
        mkdir -p $(Build.ArtifactStagingDirectory)/hostlogswindows
        cd kubernetes/windows

        az --version
        az account show
        az account set -s ${{ variables.subscription }}
        az acr login -n ${{ variables.containerRegistry }}

        @{"image.name"="${{ variables.repoImageName }}:$(windowsImageTag)"} | ConvertTo-Json -Compress | Out-File -Encoding ascii $(Build.ArtifactStagingDirectory)/windows/metadata.json

        if ("$(Build.Reason)" -ne "PullRequest") {
           docker manifest create ${{ variables.repoImageName }}:$(windowsImageTag) ${{ variables.repoImageName }}:$(windowsImageTag)-$(windows2019BaseImageVersion) ${{ variables.repoImageName }}:$(windowsImageTag)-$(windows2022BaseImageVersion)
           docker manifest push ${{ variables.repoImageName }}:$(windowsImageTag)
        }
  - task: AzureArtifacts.manifest-generator-task.manifest-generator-task.ManifestGeneratorTask@0
    displayName: 'Generation Task'
    condition: eq(variables.IS_PR, true)
    inputs:
      BuildDropPath: '$(Build.ArtifactStagingDirectory)/windows'
      DockerImagesToScan: 'mcr.microsoft.com/windows/servercore:ltsc2019, mcr.microsoft.com/windows/servercore:ltsc2022'

  - task: AzureArtifacts.manifest-generator-task.manifest-generator-task.ManifestGeneratorTask@0
    displayName: 'Generation Task'
    condition: eq(variables.IS_PR, false)
    inputs:
      BuildDropPath: '$(Build.ArtifactStagingDirectory)/windows'
      DockerImagesToScan: 'mcr.microsoft.com/windows/servercore:ltsc2019, mcr.microsoft.com/windows/servercore:ltsc2022, ${{ variables.repoImageName }}:$(windowsImageTag)'
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: drop