kind: ConfigMap
apiVersion: v1
data:
  schema-version:
    #string.used by agent to parse config. supported versions are {v1}. Configs with other schema versions will be rejected by the agent.
    v1
  config-version:
    #string.used by customer to keep track of this config file's version in their source control/repository (max allowed 10 chars, other chars will be truncated)
    ver1
  hostlogs-settings: |-
    [hostlogs_settings.geneva_logs_config]
      authid =  "VALUE_AUTH_ID"         # object_id#<guid> or client_id#<guid> or mi_res_id#<identity resource id>
      environment = "VALUE_ENVIRONMENT"                # Supported values Test, Stage, DiagnosticsProd, FirstpartyProd, BillingProd, ExternalProd, CaMooncake, CaFairfax, CaBlackforest
      account = "VALUE_ACCOUNT"       # name of the Geneva Logs account
      namespace = "VALUE_ACCOUNT_NAMESPACE"     # name of the Geneva Logs account namespace
      configversion = "VALUE_CONFIG_VERSION"               # config version of the agent xml config.
metadata:
  name: container-azm-ms-hostlogsconfig
  namespace: kube-system