---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit-read
rules:
  - apiGroups: [""]
    resources:
      - namespaces
      - pods
      - nodes
      - nodes/proxy
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit-read
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit-read
subjects:
  - kind: ServiceAccount
    name: fluent-bit
    namespace: log-fwd
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:serviceaccounts
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
data:
  # Configuration files: server, input, filters and output
  # ======================================================
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020
        storage.path  /var/log/flb-storage/
        storage.sync              normal
        storage.checksum          off
        storage.backlog.mem_limit 50M

    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-fwd-fluentd.conf
    # @INCLUDE output-null.conf

  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        # Path              /var/log/containers/*.log
        # Exclude_Path      /var/log/containers/*_kube-system_*.log,/var/log/containers/*_log-fwd_*.log
        # multiline.parser  docker, cri
        Parser            cri
        DB                /var/log/flb_kube.db
        DB.locking        true
        Mem_Buf_Limit     10MB
        Skip_Long_Lines   On
        Refresh_Interval  10
        storage.type  filesystem

  filter-kubernetes.conf: |
    # [FILTER]
    #     Name                kubernetes
    #     Match               kube.*
    #     #Kube_URL            https://kubernetes.default.svc:443
    #     Kube_URL            https://kubernetes.default.svc.cluster.local:443
    #     Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    #     Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
    #     Kube_Tag_Prefix     kube.var.log.containers.
    #     Merge_Log           On
    #     Merge_Log_Key       log_processed
    #     Labels Off
    #     Annotations Off
    #     K8S-Logging.Parser  On
    #     K8S-Logging.Exclude On
    #     Buffer_Size         512k
    #     # Kube_meta_preload_cache_dir /var/run/kube_meta_cache
    #     # Use_Kubelet         false
    #     # Kubelet_Port        10250

    # [FILTER]
    #     Name nest
    #     Match kube.*
    #     Operation lift
    #     Nested_under kubernetes
    #     Add_prefix   kubernetes_

    # [FILTER]
    #     Name modify
    #     Match kube.*
    #     Remove kubernetes_container_image
    #     Remove kubernetes_docker_id
    #     Remove kubernetes_pod_id
    #     Remove kubernetes_host
    #     Remove kubernetes_container_hash

    # [FILTER]
    #     Name                rewrite_tag
    #     Match               kube.*
    #     Rule                $kubernetes_namespace_name ^(.*)$ cosmic.$kubernetes_namespace_name.$kubernetes_pod_name.$kubernetes_container_name.log false

  output-fwd-fluentd.conf: |
    [OUTPUT]
      Name file
      Match *
      Path /var/log/

    # [OUTPUT]
    #     Name          forward
    #     Match         cosmic.*
    #     Host          geneva-services-fluentd.tel-pipe.svc.cluster.local
    #     Port          24224
    #     storage.total_limit_size  50M

  parsers.conf: |
    [PARSER]
        # http://rubular.com/r/tjUt3Awgg4
        Name cri
        Format regex
        Regex ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<message>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentbit
  labels:
    app.kubernetes.io/name: fluentbit
spec:
  selector:
    matchLabels:
      name: fluentbit
  template:
    metadata:
      labels:
        name: fluentbit
      annotations:
        fluentbit.io/exclude: "true"
    spec:
      nodeSelector:
        kubernetes.io/os: "linux"
      serviceAccountName: fluent-bit
      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:1.9
        imagePullPolicy: Always
        ports:
          - containerPort: 2020
        volumeMounts:
        - name: host-log
          mountPath: /var/log
        - name: containerlog-path
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/
        resources:
          limits:
            cpu: 1000m
            memory: 1500Mi
          requests:
            cpu: 300m
            memory: 300Mi
      terminationGracePeriodSeconds: 10
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      volumes:
      - name: host-log
        hostPath:
          path: /var/log
      - name: containerlog-path
        hostPath:
          path: /var/lib/docker/containers
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config
      tolerations:
      - key: kubernetes.io/os
        operator: "Equal"
        value: windows
        effect: NoSchedule
